services:
  web:
    image: traefik/whoami:latest
    env_file:
      - ../../env/global.env
      - ../../env/whoami.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=le
      - traefik.http.services.whoami.loadbalancer.server.port=${WHOAMI_INTERNAL_PORT}
    restart: unless-stopped
networks:
  default:
    external: true
    name: proxy_default
