services:
  web:
    image: ghcr.io/wtrvgl/exolan/web:v0.1.3
    container_name: exolan-web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.routers.exolan.rule=Host(`exolan.be`)
      - traefik.http.routers.exolan.entrypoints=websecure
      - traefik.http.routers.exolan.tls.certresolver=le
      - traefik.http.services.exolan.loadbalancer.server.port=80
      # Handle www on TLS and redirect to apex
      - traefik.http.routers.exolan-www.rule=Host(`www.exolan.be`)
      - traefik.http.routers.exolan-www.entrypoints=websecure
      - traefik.http.routers.exolan-www.tls.certresolver=le
      - traefik.http.middlewares.exolan-www-redirect.redirectregex.regex=^https?://www\.exolan\.be/(.*)
      - traefik.http.middlewares.exolan-www-redirect.redirectregex.replacement=https://exolan.be/$1
      - traefik.http.middlewares.exolan-www-redirect.redirectregex.permanent=true
      - traefik.http.routers.exolan-www.middlewares=exolan-www-redirect
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy_default
